version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: ${PROJECT_NAME}_web
    volumes:
      - ./src:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmvc.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.phpmvc.entrypoints=web"
      - "traefik.http.services.phpmvc.loadbalancer.server.port=80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.dashboard.address=:8081"  # New entrypoint for the dashboard
      - "--api.dashboard=true"
      - "--api.debug=true"
    ports:
      - "80:80"      # Traefik routes HTTP traffic to your app on port 80
      - "8080:8080"  # Traefik Dashboard on port 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=dashboard"

volumes:
  db_data: