# docker/db/Dockerfile

FROM mariadb:latest

# Set MariaDB configurations
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=your_database_name
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

EXPOSE 3306